---
title: "PSTAT194"
author: "HaozeZhu"
date: "6/2/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr) ##please update it to the latest version 
library(stringr)
library(zoo)
library(ggplot2)
library(urbnmapr)

##some functions we wrote for the analysis

source(file = "/Users/walterzhu/Rstudio/PSTAT120C/covid-19/data_and_functions/functions_covid19.R")



##get the data from JHU CSSE, which contain the death and confirmed cases at county-level
base = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/'
death = 'time_series_covid19_deaths_'
confirm = 'time_series_covid19_confirmed_'
wkd = '/Users/walterzhu/Rstudio/PSTAT120C/covid-19/'

###up-to-date US death and confirmed cases
us_death = read.csv(paste0(wkd,death,"US.csv"))
us_confirm = read.csv(paste0(wkd,confirm,"US.csv"))

##dimension
dim(us_death)
dim(us_confirm)
##get the column names of the data 
col_names = colnames(us_death)
all_dates = as.Date(paste0(str_sub(col_names[13:dim(us_death)[2]], 2, -1)),tryFormats = c("%m.%d.%y"))
##these are the dates from the data set 
all_dates

##this site provide the confirmed state-level total test from which you can get the positive rate  
covid19_project_url = "https://api.covidtracking.com/v1/states/daily.csv"

covid_19_project = read.csv(covid19_project_url)

covid_19_project$date = as.Date(as.character(covid_19_project$date), "%Y %m %d")
##note that this date starts from  the current day
covid_19_project$date


##nation level analysis
##nation level daily confirmed cases, plot and 
nation_death = us_death %>%
  dplyr::filter(Province_State == "California")

###observed confirmed cases
nation_confirmed = us_confirm %>%
  dplyr::filter(Province_State == "California")


###the first row of the state death data set and you can see the format
nation_death[1,]
###get the cumulative death toll and confirmed cases
nation_death_sum = apply(nation_death[,12:dim(nation_death)[2]], 2, sum)

nation_confirmed_sum = apply(nation_confirmed[,12:dim(nation_confirmed)[2]], 2, sum)

##get  dates you want to analyze  
start_date = as.Date("2021-11-01")

end_date = as.Date("2022-4-01")




##the deaths and confirmed cases for the state on the selected dates
nation_death_selected = nation_death_sum[1 + which(all_dates %in% seq.Date(start_date, end_date, by=1))]
nation_confirmed_selected = nation_confirmed_sum[which(all_dates %in% seq.Date(start_date, end_date, by=1))]

nation_death_selected=as.numeric(nation_death_selected)
nation_confirmed_selected=as.numeric(nation_confirmed_selected)

##plot cumulative confirmed cases and death
date_selected=seq.Date(start_date, end_date, by=1)
par(mfrow=c(1,2))
plot(date_selected,nation_confirmed_selected,xlab='date',ylab='cumulative observed confirmed cases',type='l')
plot(date_selected,nation_death_selected,xlab='date',ylab='cumulative death toll',type='l')
dev.off() ##close it

##daily increase between each date
daily_date_selected=date_selected[2:length(date_selected)]

##let's get the daily confirmed cases 
nation_confirmed_selected_daily=nation_confirmed_selected[2:length(nation_confirmed_selected)]-nation_confirmed_selected[1:(length(nation_confirmed_selected)-1)]
##create a data frame
daily_confirmed_nation_df = data.frame(date = daily_date_selected, value = nation_confirmed_selected_daily)

##let's get the daily death cases 
nation_death_selected_daily=nation_death_selected[2:length(nation_death_selected)]-nation_death_selected[1:(length(nation_death_selected)-1)]
##create a data frame
daily_death_nation_df = data.frame(date = daily_date_selected, value = nation_death_selected_daily)

###daily confirmed cases in US
daily_confirmed_nation_df %>%
  ggplot(aes(x=date, y=value)) +
  geom_bar(stat = 'identity', color="white",  fill="#ff8540", width = 1) +
  ylab("Daily confirmed cases in  US")+
  xlab("Date")+ 
  theme(text = element_text(size = 20),
        legend.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.key.width=unit(1,"cm"),
        axis.text.y = element_text(angle=90, hjust=1))
dev.off()
###daily death in US
daily_death_nation_df %>%
  ggplot(aes(x=date, y=value)) +
  geom_bar(stat = 'identity', color="white",  fill="#0000FF", width = 1) +
  ylab("Daily Death cases in US")+
  xlab("Date")+ 
  theme(text = element_text(size = 20),
        legend.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.key.width=unit(1,"cm"),
        axis.text.y = element_text(angle=90, hjust=1))
dev.off()

##let's obtain a seven-day average of the smoothed version of the confirmed cases and deaths

nation_confirmed_selected_daily_avg = data_seven_day_smoothing(nation_confirmed_selected_daily)

daily_confirmed_nation_smoothed_df = data.frame(date = daily_date_selected, value = nation_confirmed_selected_daily_avg)

nation_death_selected_daily_avg = data_seven_day_smoothing(nation_death_selected_daily)

daily_death_nation_smoothed_df = data.frame(date = daily_date_selected, value = nation_death_selected_daily_avg)

##plot the smoothed version 

###daily confirmed cases in US
daily_confirmed_nation_smoothed_df %>%
  ggplot(aes(x=date, y=value)) +
  geom_bar(stat = 'identity', color="white",  fill="#ff8540", width = 1) +
  ylab("7-day averaged daily confirmed cases in  US")+
  xlab("Date")+ 
  theme(text = element_text(size = 20),
        legend.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.key.width=unit(1,"cm"),
        axis.text.y = element_text(angle=90, hjust=1))
dev.off()
###daily death in US
daily_death_nation_smoothed_df %>%
  ggplot(aes(x=date, y=value)) +
  geom_bar(stat = 'identity', color="white",  fill="#0000FF", width = 1) +
  ylab("7-day averaged daily death cases in US")+
  xlab("Date")+ 
  theme(text = element_text(size = 20),
        legend.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        legend.key.width=unit(1,"cm"),
        axis.text.y = element_text(angle=90, hjust=1))
dev.off()
```

